# Generated by Django 5.2.13 on 2026-04-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('quantity', models.PositiveIntegerField(verbose_name='购买数量')),
                ('contact', models.CharField(max_length=160, verbose_name='联系方式')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单金额')),
                ('pay_type', models.CharField(default='alipay', max_length=20, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('expired', '已过期'), ('cancelled', '已取消')], default='pending', max_length=16, verbose_name='订单状态')),
                ('expires_at', models.DateTimeField(verbose_name='支付过期时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('delivery_items', models.JSONField(blank=True, default=list, verbose_name='发货内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='easypay', max_length=40, verbose_name='支付渠道')),
                ('trade_no', models.CharField(blank=True, max_length=80, verbose_name='渠道流水号')),
                ('out_trade_no', models.CharField(max_length=80, verbose_name='商户订单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('ignored', '已忽略')], max_length=16, verbose_name='流水状态')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='原始回调')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '支付流水',
                'verbose_name_plural': '支付流水',
            },
        ),
    ]
