# Generated by Django 5.2.13 on 2026-04-28 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '后台使用指南',
                'verbose_name_plural': '后台使用指南',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CodexImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Codex 卡密一键导入',
                'verbose_name_plural': 'Codex 卡密一键导入',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='前台显示')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='数字越小越靠前。', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：AI 工具、数字权益。', max_length=80, unique=True, verbose_name='分类名称')),
                ('slug', models.SlugField(help_text='英文或拼音，用在系统内部区分分类。', max_length=100, unique=True, verbose_name='分类标识')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='数字越小越靠前。', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='前台显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='例如：site_name、support_contact。', max_length=80, unique=True, verbose_name='配置键')),
                ('value', models.TextField(blank=True, verbose_name='配置值')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='显示名称')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='商品名称')),
                ('description', models.TextField(blank=True, help_text='展示在前台商品卡片中，建议写清楚用途和交付内容。', verbose_name='商品说明')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售价')),
                ('image_url', models.URLField(blank=True, help_text='可选；填写图片 URL 后前台会展示。', verbose_name='商品图片地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='前台上架')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='数字越小越靠前。', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CardSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_secret', models.TextField(verbose_name='加密卡密')),
                ('status', models.CharField(choices=[('available', '可售'), ('reserved', '已预留'), ('sold', '已售出')], default='available', max_length=16, verbose_name='库存状态')),
                ('reserved_until', models.DateTimeField(blank=True, null=True, verbose_name='预留到期时间')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='售出时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reserved_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_cards', to='orders.order', verbose_name='预留订单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='shop.product', verbose_name='所属商品')),
            ],
            options={
                'verbose_name': '卡密库存',
                'verbose_name_plural': '卡密库存',
                'indexes': [models.Index(fields=['product', 'status'], name='shop_cardse_product_29f44a_idx'), models.Index(fields=['reserved_until'], name='shop_cardse_reserve_8c6cae_idx')],
            },
        ),
    ]
