# Generated by Django 5.2.13 on 2026-04-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsecret',
            name='status',
            field=models.CharField(choices=[('available', '可售'), ('reserved', '已预留'), ('sold', '已售出'), ('void', 'Voided')], default='available', max_length=16, verbose_name='库存状态'),
        ),
    ]
