from django.urls import path

from .views import (
    AdminDashboardView,
    AdminMeView,
    AnnouncementDetailView,
    AnnouncementListCreateView,
    CardImportCommitView,
    CardImportPreviewView,
    CardListView,
    CancelOrderView,
    CategoryDetailView,
    CategoryListCreateView,
    MarkPaidView,
    OrderDetailView,
    OrderListView,
    PaymentDetailView,
    PaymentListView,
    PaymentResolveView,
    ProductDetailView,
    ProductListCreateView,
    RedeliverOrderView,
    ReleaseStockView,
    SiteConfigDetailView,
    SiteConfigListView,
    OperationLogListView,
    UserDetailView,
    UserListView,
    ReplaceCardView,
)


urlpatterns = [
    path("me", AdminMeView.as_view()),
    path("dashboard", AdminDashboardView.as_view()),
    path("products", ProductListCreateView.as_view()),
    path("products/<int:pk>", ProductDetailView.as_view()),
    path("categories", CategoryListCreateView.as_view()),
    path("categories/<int:pk>", CategoryDetailView.as_view()),
    path("announcements", AnnouncementListCreateView.as_view()),
    path("announcements/<int:pk>", AnnouncementDetailView.as_view()),
    path("cards/import/preview", CardImportPreviewView.as_view()),
    path("cards/import/commit", CardImportCommitView.as_view()),
    path("cards", CardListView.as_view()),
    path("orders", OrderListView.as_view()),
    path("orders/<int:order_id>/mark-paid", MarkPaidView.as_view()),
    path("orders/<int:order_id>/cancel", CancelOrderView.as_view()),
    path("orders/<int:order_id>/redeliver", RedeliverOrderView.as_view()),
    path("orders/<int:order_id>/replace-card", ReplaceCardView.as_view()),
    path("orders/<int:order_id>/release-stock", ReleaseStockView.as_view()),
    path("orders/<int:pk>", OrderDetailView.as_view()),
    path("payments", PaymentListView.as_view()),
    path("payments/<int:payment_id>/resolve", PaymentResolveView.as_view()),
    path("payments/<int:pk>", PaymentDetailView.as_view()),
    path("users", UserListView.as_view()),
    path("users/<int:pk>", UserDetailView.as_view()),
    path("site-config", SiteConfigListView.as_view()),
    path("site-config/<str:key>", SiteConfigDetailView.as_view()),
    path("logs", OperationLogListView.as_view()),
]
